'use strict';
// Unit tests for sandbox.js (docs/sandbox-plan.md M1) — the pure parts (compose
// bytes, port bump, image resolution, ps parsing) plus the factory's spawn/
// docker-mocked behavior (detection, idempotent peer registration, up/down).

const test = require('node:test');
const assert = require('node:assert');
const { EventEmitter } = require('node:events');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

// A throwaway userData dir for the tests that let writeComposeFile actually
// write; removed on process exit.
const TMP_USERDATA = fs.mkdtempSync(path.join(os.tmpdir(), 'clx-sandbox-'));
process.on('exit', () => { try { fs.rmSync(TMP_USERDATA, { recursive: true, force: true }); } catch {} });

const {
  createSandbox,
  resolveImage, resolvePorts, nextFreePort, generateCompose,
  parseOwnPorts, parsePsRows, parseComposeState,
  DEFAULT_CONFIG, CONTAINER_PORTS, SANDBOX_PEER_ID,
} = require('../sandbox');

// ── resolveImage ────────────────────────────────────────────────────────────

test('resolveImage: packaged app pins the GHCR version tag', () => {
  const r = resolveImage({ isPackaged: true, appVersion: '2.24.0', override: null, repoRoot: '/repo' });
  assert.deepStrictEqual(r, { kind: 'image', image: 'ghcr.io/avirtual/clodex:2.24.0' });
});

test('resolveImage: dev build:s from the repo checkout (no GHCR)', () => {
  const r = resolveImage({ isPackaged: false, appVersion: '2.24.0', override: null, repoRoot: '/repo' });
  assert.deepStrictEqual(r, { kind: 'build', context: '/repo', dockerfile: 'docker/web/Dockerfile' });
});

test('resolveImage: an explicit override wins in any state', () => {
  const packaged = resolveImage({ isPackaged: true, appVersion: '2.24.0', override: 'my/img:tag', repoRoot: '/repo' });
  const dev = resolveImage({ isPackaged: false, appVersion: '2.24.0', override: 'my/img:tag', repoRoot: '/repo' });
  assert.deepStrictEqual(packaged, { kind: 'image', image: 'my/img:tag' });
  assert.deepStrictEqual(dev, { kind: 'image', image: 'my/img:tag' });
});

// ── port bump ───────────────────────────────────────────────────────────────

test('nextFreePort: returns the desired port when free', () => {
  assert.strictEqual(nextFreePort(7810, () => false, new Set()), 7810);
});

test('nextFreePort: bumps past a listener', () => {
  const busy = new Set([7810, 7811]);
  assert.strictEqual(nextFreePort(7810, (p) => busy.has(p), new Set()), 7812);
});

test('nextFreePort: skips ports already claimed in this generation', () => {
  const taken = new Set([7810]);
  assert.strictEqual(nextFreePort(7810, () => false, taken), 7811);
  assert.ok(taken.has(7811));
});

test('resolvePorts: all three free → the configured defaults', () => {
  const ports = resolvePorts(DEFAULT_CONFIG, () => false);
  assert.deepStrictEqual(ports, { web: 7810, wirescope: 7811, wire: 7820 });
});

test('resolvePorts: collisions bump each port, no two collapse onto one', () => {
  // 7810 (web default) and 7820 (wire default) are held; web bumps to 7811, but
  // wirescope's default IS 7811, so it must bump again — and never onto web's.
  const busy = new Set([7810, 7820]);
  const ports = resolvePorts(DEFAULT_CONFIG, (p) => busy.has(p));
  assert.strictEqual(ports.web, 7811);
  assert.strictEqual(ports.wirescope, 7812); // 7811 taken by web this generation
  assert.strictEqual(ports.wire, 7821);
  // Distinctness invariant.
  assert.strictEqual(new Set([ports.web, ports.wirescope, ports.wire]).size, 3);
});

// ── generateCompose ─────────────────────────────────────────────────────────

const DEV_IMAGE = { kind: 'build', context: '/repo', dockerfile: 'docker/web/Dockerfile' };
const PORTS = { web: 7810, wirescope: 7811, wire: 7820 };

test('generateCompose: dev build variant with a named work volume', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: null });
  assert.match(yaml, /^# GENERATED by Clodex/m);
  assert.match(yaml, /hostname: sandbox/);
  assert.match(yaml, /build:\n {6}context: \/repo\n {6}dockerfile: docker\/web\/Dockerfile/);
  // Three loopback publishes host<config> → container<fixed>.
  assert.match(yaml, /- "127\.0\.0\.1:7810:8080"/);
  assert.match(yaml, /- "127\.0\.0\.1:7811:7800"/);
  assert.match(yaml, /- "127\.0\.0\.1:7820:7900"/);
  // Named work volume + its declaration.
  assert.match(yaml, /- clodex-work:\/home\/clodex\/work/);
  assert.match(yaml, /^ {2}clodex-work:$/m);
  // Wirescope public URL tracks the host port.
  assert.match(yaml, /CLODEX_WIRESCOPE_PUBLIC_URL: "\$\{CLODEX_WIRESCOPE_PUBLIC_URL:-http:\/\/localhost:7811\}"/);
  // Compose interpolations survive untouched (not eaten by JS).
  assert.match(yaml, /CLODEX_WEB_TOKEN: "\$\{CLODEX_WEB_TOKEN:-\}"/);
  // Fixed lifecycle bits mirrored from docker/web/compose.yaml.
  assert.match(yaml, /init: true/);
  assert.match(yaml, /restart: always/);
  assert.match(yaml, /healthcheck:/);
  // No image: line in the dev/build variant, no env_file without an auth file.
  assert.doesNotMatch(yaml, /^ {4}image:/m);
  assert.doesNotMatch(yaml, /env_file:/);
});

test('generateCompose: packaged image variant with a host bind-mount', () => {
  const image = { kind: 'image', image: 'ghcr.io/avirtual/clodex:2.24.0' };
  const yaml = generateCompose({ image, ports: PORTS, workDir: '/Users/me/work', authEnvFile: null });
  assert.match(yaml, /^ {4}image: ghcr\.io\/avirtual\/clodex:2\.24\.0$/m);
  assert.doesNotMatch(yaml, /build:/);
  // Bind mount (double-quoted), and NO clodex-work named volume declared.
  assert.match(yaml, /- "\/Users\/me\/work:\/home\/clodex\/work"/);
  assert.doesNotMatch(yaml, /- clodex-work:\/home\/clodex\/work/);
  assert.doesNotMatch(yaml, /^ {2}clodex-work:$/m);
});

test('generateCompose: bumped ports flow into every publish + the public URL', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: { web: 7811, wirescope: 7812, wire: 7821 }, workDir: null, authEnvFile: null,
  });
  assert.match(yaml, /- "127\.0\.0\.1:7811:8080"/);
  assert.match(yaml, /- "127\.0\.0\.1:7812:7800"/);
  assert.match(yaml, /- "127\.0\.0\.1:7821:7900"/);
  assert.match(yaml, /CLODEX_WIRESCOPE_PUBLIC_URL:.*localhost:7812/);
});

test('generateCompose: auth env_file referenced by path, never inlined (M4 hook)', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: '/data/sandbox/auth.env',
  });
  // Quoted like the workDir bind — userData paths carry spaces on macOS.
  assert.match(yaml, /env_file:\n {6}- "\/data\/sandbox\/auth\.env"/);
  // A hook point only — no secret material lands in the bytes.
  assert.doesNotMatch(yaml, /CLAUDE_CODE_OAUTH_TOKEN/);
});

test('generateCompose: healthcheck probes the fixed container web port', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: null });
  assert.ok(yaml.includes(`http://127.0.0.1:${CONTAINER_PORTS.web}/healthz`));
});

test('generateCompose: a workDir with spaces is double-quoted so YAML keeps it verbatim', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, workDir: '/Users/me/My Work #1', authEnvFile: null,
  });
  assert.match(yaml, /- "\/Users\/me\/My Work #1:\/home\/clodex\/work"/);
});

test('generateCompose: read-only host library binds layered on clodex-dot (M5 Decision 7)', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: null, libDir: '/Users/me/.clodex',
  });
  // Three ro binds: skills, agents, and one `library` dir (covers prompts+exec).
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/skills:\/home\/clodex\/\.clodex\/skills:ro"/);
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/agents:\/home\/clodex\/\.clodex\/agents:ro"/);
  assert.match(yaml, /- "\/Users\/me\/\.clodex\/library:\/home\/clodex\/\.clodex\/library:ro"/);
  // Layered AFTER clodex-dot (shadowing its subpaths) and BEFORE claude-auth;
  // the clodex-dot volume itself stays — the box still writes run/, messages/,
  // pending/ into it underneath the read-only library binds.
  assert.match(yaml, /- clodex-dot:\/home\/clodex\/\.clodex\n( +- "[^\n]*:ro"\n){3} +- claude-auth:/);
  // One `library` bind covers prompts + exec — no separate exec mount.
  assert.doesNotMatch(yaml, /\/exec:ro/);
});

test('generateCompose: no library binds when libDir is absent (guard for none-passing callers)', () => {
  const yaml = generateCompose({ image: DEV_IMAGE, ports: PORTS, workDir: null, authEnvFile: null });
  assert.doesNotMatch(yaml, /:ro"/);
  assert.doesNotMatch(yaml, /home\/clodex\/\.clodex\/skills/);
});

// ── parseOwnPorts (self-collision guard) ────────────────────────────────────

test('parseOwnPorts: extracts the three published host ports from a compose file', () => {
  const yaml = generateCompose({
    image: DEV_IMAGE, ports: { web: 7811, wirescope: 7812, wire: 7821 }, workDir: null, authEnvFile: null,
  });
  assert.deepStrictEqual(parseOwnPorts(yaml).sort((a, b) => a - b), [7811, 7812, 7821]);
});

test('parseOwnPorts: empty for missing/garbage input', () => {
  assert.deepStrictEqual(parseOwnPorts(''), []);
  assert.deepStrictEqual(parseOwnPorts(null), []);
  assert.deepStrictEqual(parseOwnPorts('services:\n  clodex:\n    image: x'), []);
});

// ── compose ps parsing ──────────────────────────────────────────────────────

test('parsePsRows: reads a JSON array', () => {
  const rows = parsePsRows('[{"Service":"clodex","State":"running"}]');
  assert.strictEqual(rows.length, 1);
  assert.strictEqual(rows[0].Service, 'clodex');
});

test('parsePsRows: reads newline-delimited JSON objects, skipping garbage', () => {
  const rows = parsePsRows('{"Service":"clodex","State":"exited"}\nnot json\n{"Service":"x","State":"running"}');
  assert.strictEqual(rows.length, 2);
  assert.strictEqual(rows[0].State, 'exited');
});

test('parseComposeState: running / exited / absent', () => {
  assert.strictEqual(parseComposeState('[{"Service":"clodex","State":"running"}]'), 'running');
  assert.strictEqual(parseComposeState('[{"Service":"clodex","State":"exited"}]'), 'exited');
  assert.strictEqual(parseComposeState(''), 'absent');
  assert.strictEqual(parseComposeState('[]'), 'absent');
  // Falls back to Status text when State is absent.
  assert.strictEqual(parseComposeState('[{"Service":"clodex","Status":"Up 3 minutes"}]'), 'running');
});

// ── factory: detection (spawn mocked) ───────────────────────────────────────

// A fake child process: emits 'error' or 'exit' on the next tick.
function fakeSpawn(behavior) {
  return () => {
    const child = new EventEmitter();
    child.stdout = new EventEmitter();
    child.stderr = new EventEmitter();
    child.kill = () => {};
    process.nextTick(() => {
      if (behavior.error) child.emit('error', behavior.error);
      else {
        if (behavior.stdout) child.stdout.emit('data', behavior.stdout);
        if (behavior.stderr) child.stderr.emit('data', behavior.stderr);
        child.emit('exit', behavior.code ?? 0);
      }
    });
    return child;
  };
}

test('detect: docker missing (ENOENT) → not present', async () => {
  const sb = createSandbox({ spawn: fakeSpawn({ error: Object.assign(new Error('nope'), { code: 'ENOENT' }) }) });
  assert.deepStrictEqual(await sb.detect(), { present: false, running: false });
});

test('detect: daemon down (non-zero exit) → present but not running', async () => {
  const sb = createSandbox({ spawn: fakeSpawn({ code: 1 }) });
  assert.deepStrictEqual(await sb.detect(), { present: true, running: false });
});

test('detect: healthy (exit 0) → present and running', async () => {
  const sb = createSandbox({ spawn: fakeSpawn({ code: 0 }) });
  assert.deepStrictEqual(await sb.detect(), { present: true, running: true });
});

// ── factory: idempotent peer registration (settings mocked) ─────────────────

// A minimal ui-settings double: shallow-merge set, matching stores.js semantics
// for the peers array.
function fakeSettings(initial = {}) {
  let state = { peers: [], ...initial };
  return {
    _state: () => state,
    get() { return { ...state }; },
    set(partial) { state = { ...state, ...partial }; return state; },
  };
}

test('registerPeer: first call adds the sandbox row', () => {
  const settings = fakeSettings();
  let synced = 0;
  const sb = createSandbox({ getUiSettings: () => settings, syncPeerManager: () => { synced++; } });
  sb.registerPeer(7820);
  assert.deepStrictEqual(settings._state().peers, [{ id: 'sandbox', label: 'sandbox', url: 'http://127.0.0.1:7820' }]);
  assert.strictEqual(synced, 1);
});

test('registerPeer: an unchanged url writes nothing (no reconcile churn)', () => {
  const settings = fakeSettings({ peers: [{ id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820' }] });
  let synced = 0;
  const sb = createSandbox({ getUiSettings: () => settings, syncPeerManager: () => { synced++; } });
  sb.registerPeer(7820);
  assert.strictEqual(synced, 0);
});

test('registerPeer: a moved wire port updates the url in place, never duplicates', () => {
  const settings = fakeSettings({ peers: [
    { id: 'other', label: 'other', url: 'http://example/' },
    { id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820' },
  ] });
  const sb = createSandbox({ getUiSettings: () => settings });
  sb.registerPeer(7821);
  const peers = settings._state().peers;
  assert.strictEqual(peers.length, 2);
  assert.strictEqual(peers.find((p) => p.id === SANDBOX_PEER_ID).url, 'http://127.0.0.1:7821');
  assert.strictEqual(peers.find((p) => p.id === 'other').url, 'http://example/'); // untouched
});

// ── factory: up / down (spawn + settings mocked, no port probe) ─────────────

// A spawn that always reports success and never actually binds — paired with an
// isPortInUse stub so writeComposeFile's probe is deterministic and offline.
function okComposeSpawn() { return fakeSpawn({ code: 0 }); }

test('up: writes compose, brings it up, registers the peer', async () => {
  const settings = fakeSettings();
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
    isPackaged: () => false,
    repoRoot: '/repo',
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, true);
  assert.deepStrictEqual(r.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.strictEqual(settings._state().peers.length, 1);
  assert.strictEqual(settings._state().peers[0].id, 'sandbox');
  // The compose file was actually written to <userData>/sandbox/.
  assert.ok(fs.existsSync(sb.composePath()));
});

test('up: a compose failure surfaces stderr and does NOT register the peer', async () => {
  const settings = fakeSettings();
  const sb = createSandbox({
    spawn: fakeSpawn({ code: 1, stderr: 'Cannot connect to the Docker daemon' }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
    isPortInUse: () => Promise.resolve(false),
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, false);
  assert.match(r.error, /Cannot connect to the Docker daemon/);
  assert.strictEqual(settings._state().peers.length, 0);
});

test('down: succeeds and leaves the peer row in place (offline affordance)', async () => {
  const settings = fakeSettings({ peers: [{ id: SANDBOX_PEER_ID, label: 'sandbox', url: 'http://127.0.0.1:7820' }] });
  const sb = createSandbox({
    spawn: fakeSpawn({ code: 0 }),
    getUiSettings: () => settings,
    getUserDataPath: () => TMP_USERDATA,
  });
  const r = await sb.down();
  assert.strictEqual(r.ok, true);
  assert.strictEqual(settings._state().peers.length, 1); // NOT removed
});

// ── factory: re-up port stability (the self-collision fix) ──────────────────

// A userData dir unique to a test, so its compose.yaml doesn't cross-talk.
function freshUserData() {
  return fs.mkdtempSync(path.join(TMP_USERDATA, 'ud-'));
}

test('up twice with our own ports "busy" keeps the three ports byte-stable', async () => {
  const settings = fakeSettings();
  const ud = freshUserData();
  // After the first up publishes 7810/7811/7820, a live probe would see them
  // busy — the exact self-collision that used to drift the ports upward.
  const ownBusy = new Set([7810, 7811, 7820]);
  let started = false;
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: (p) => Promise.resolve(started && ownBusy.has(p)),
  });
  const first = await sb.up();
  const composeA = fs.readFileSync(sb.composePath(), 'utf8');
  started = true; // container is now "running" — its ports read busy
  const second = await sb.up();
  const composeB = fs.readFileSync(sb.composePath(), 'utf8');

  assert.deepStrictEqual(first.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.deepStrictEqual(second.ports, { web: 7810, wirescope: 7811, wire: 7820 });
  assert.strictEqual(composeA, composeB); // byte-identical regen
  // The peer url did NOT churn (one row, unchanged url).
  assert.strictEqual(settings._state().peers.length, 1);
  assert.strictEqual(settings._state().peers[0].url, 'http://127.0.0.1:7820');
});

test('up: a GENUINE squatter on 7810 (not our own port) still bumps', async () => {
  const settings = fakeSettings();
  const ud = freshUserData();
  // 7810 is held by something that is NOT our container (no prior compose file).
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: (p) => Promise.resolve(p === 7810),
  });
  const r = await sb.up();
  assert.strictEqual(r.ports.web, 7811); // bumped off the squatter
  assert.strictEqual(settings._state().peers[0].url, `http://127.0.0.1:${r.ports.wire}`);
});

// ── factory: auth token file (M4) ───────────────────────────────────────────

test('setAuthToken: writes auth.env at mode 0600 with the CLAUDE_CODE_OAUTH_TOKEN line', () => {
  const ud = freshUserData();
  const sb = createSandbox({ getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  const r = sb.setAuthToken('sk-tok-123');
  assert.deepStrictEqual(r, { ok: true, hasToken: true });
  const file = path.join(ud, 'sandbox', 'auth.env');
  assert.strictEqual(fs.readFileSync(file, 'utf8'), 'CLAUDE_CODE_OAUTH_TOKEN=sk-tok-123\n');
  assert.strictEqual(fs.statSync(file).mode & 0o777, 0o600);
  assert.strictEqual(sb.hasAuthToken(), true);
});

test('setAuthToken: trims surrounding whitespace from a pasted token', () => {
  const ud = freshUserData();
  const sb = createSandbox({ getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  sb.setAuthToken('  sk-pasted\n');
  const file = path.join(ud, 'sandbox', 'auth.env');
  assert.strictEqual(fs.readFileSync(file, 'utf8'), 'CLAUDE_CODE_OAUTH_TOKEN=sk-pasted\n');
});

test('setAuthToken: an empty/blank/null token is rejected and writes no file', () => {
  const ud = freshUserData();
  const sb = createSandbox({ getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  assert.strictEqual(sb.setAuthToken('   ').ok, false);
  assert.strictEqual(sb.setAuthToken('').ok, false);
  assert.strictEqual(sb.setAuthToken(null).ok, false);
  assert.strictEqual(sb.hasAuthToken(), false);
});

test('getConfig.hasToken tracks the auth.env file; setConfig never persists it', () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({ getUiSettings: () => settings, getUserDataPath: () => ud });
  assert.strictEqual(sb.getConfig().hasToken, false);
  sb.setAuthToken('sk-x');
  assert.strictEqual(sb.getConfig().hasToken, true);
  // Persisting other config must not leak the derived flag into the store.
  sb.setConfig({ webPort: 7999 });
  assert.strictEqual('hasToken' in settings._state().sandbox, false);
});

test('clearAuthToken: deletes the file, idempotent when already absent', () => {
  const ud = freshUserData();
  const sb = createSandbox({ getUiSettings: () => fakeSettings(), getUserDataPath: () => ud });
  sb.setAuthToken('sk-y');
  assert.strictEqual(sb.hasAuthToken(), true);
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false });
  assert.strictEqual(sb.hasAuthToken(), false);
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false }); // no-op, still ok
});

test('writeComposeFile: references the auth env_file once the token exists, never the value', async () => {
  const ud = freshUserData();
  const sb = createSandbox({
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  // No token yet → no env_file line.
  await sb.writeComposeFile();
  let yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.doesNotMatch(yaml, /env_file/);
  // Seed the token → next regen references the file by path; the secret value
  // (and the var name it's keyed under) never appear in the compose bytes.
  sb.setAuthToken('sk-secret-should-never-appear');
  await sb.writeComposeFile();
  yaml = fs.readFileSync(sb.composePath(), 'utf8');
  const authPath = path.join(ud, 'sandbox', 'auth.env');
  assert.ok(yaml.includes('env_file:'));
  // Quoted like the workDir bind — userData paths carry spaces on macOS.
  assert.ok(yaml.includes(`- "${authPath}"`));
  assert.doesNotMatch(yaml, /sk-secret-should-never-appear/);
  assert.doesNotMatch(yaml, /CLAUDE_CODE_OAUTH_TOKEN/);
});

test('writeComposeFile: ensure-dirs the host library sources and binds them read-only', async () => {
  const ud = freshUserData();
  const reg = fs.mkdtempSync(path.join(TMP_USERDATA, 'reg-'));
  const sb = createSandbox({
    getUiSettings: () => fakeSettings(),
    getUserDataPath: () => ud,
    registryDir: reg,
    isPortInUse: () => Promise.resolve(false),
  });
  await sb.writeComposeFile();
  // The three source dirs were created under the injected host registry root,
  // so docker never binds a missing source.
  for (const d of ['skills', 'agents', 'library']) {
    assert.ok(fs.existsSync(path.join(reg, d)), `${d} ensure-dir'd`);
  }
  // And the compose bytes bind them read-only into the box.
  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.ok(yaml.includes(`- "${path.join(reg, 'skills')}:/home/clodex/.clodex/skills:ro"`));
  assert.ok(yaml.includes(`- "${path.join(reg, 'agents')}:/home/clodex/.clodex/agents:ro"`));
  assert.ok(yaml.includes(`- "${path.join(reg, 'library')}:/home/clodex/.clodex/library:ro"`));
});

// ── factory: remote-wire token auto-provision (remote-auth chunk 4) ──────────

test('up: auto-provisions CLODEX_REMOTE_TOKEN into auth.env, compose stays token-clean, peer carries the Bearer', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  const r = await sb.up();
  assert.strictEqual(r.ok, true);

  // A random hex secret landed in the 0600 auth.env under its own key.
  const authFile = path.join(ud, 'sandbox', 'auth.env');
  const authBody = fs.readFileSync(authFile, 'utf8');
  assert.match(authBody, /^CLODEX_REMOTE_TOKEN=[0-9a-f]{64}$/m);
  assert.strictEqual(fs.statSync(authFile).mode & 0o777, 0o600);
  const token = authBody.match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];

  // The compose bytes reference only the env_file — never the key name or value
  // (env_file injects it into the container env, so no compose `environment:` line
  // is needed). This is the chunk-4 leak-guard.
  const yaml = fs.readFileSync(sb.composePath(), 'utf8');
  assert.ok(yaml.includes('env_file:'));
  assert.doesNotMatch(yaml, /CLODEX_REMOTE_TOKEN/);
  assert.ok(!yaml.includes(token), 'the secret value never appears in the compose bytes');

  // The desktop-side sandbox peer entry carries the same token as its Bearer.
  assert.strictEqual(settings._state().peers[0].id, SANDBOX_PEER_ID);
  assert.strictEqual(settings._state().peers[0].token, token);
});

test('up twice: the remote token (and the peer Bearer) stay stable — provisioned once, never rerolled', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  await sb.up();
  const first = fs.readFileSync(path.join(ud, 'sandbox', 'auth.env'), 'utf8');
  await sb.up();
  const second = fs.readFileSync(path.join(ud, 'sandbox', 'auth.env'), 'utf8');
  assert.strictEqual(first, second, 'the token is idempotent across re-up');
  // One peer row, unchanged token — no reconcile churn from a re-roll.
  assert.strictEqual(settings._state().peers.length, 1);
  assert.match(settings._state().peers[0].token, /^[0-9a-f]{64}$/);
});

test('setAuthToken preserves an existing remote token line (multi-key write)', async () => {
  const ud = freshUserData();
  const settings = fakeSettings();
  const sb = createSandbox({
    spawn: okComposeSpawn(),
    getUiSettings: () => settings,
    getUserDataPath: () => ud,
    isPortInUse: () => Promise.resolve(false),
  });
  // up() provisions the remote token first.
  await sb.up();
  const authFile = path.join(ud, 'sandbox', 'auth.env');
  const remote = fs.readFileSync(authFile, 'utf8').match(/CLODEX_REMOTE_TOKEN=([0-9a-f]+)/)[1];

  // Now the operator sets an OAuth token — the remote token must survive.
  assert.deepStrictEqual(sb.setAuthToken('sk-oauth-added'), { ok: true, hasToken: true });
  let body = fs.readFileSync(authFile, 'utf8');
  assert.match(body, /^CLAUDE_CODE_OAUTH_TOKEN=sk-oauth-added$/m);
  assert.match(body, new RegExp(`^CLODEX_REMOTE_TOKEN=${remote}$`, 'm'));

  // Clearing the OAuth token leaves the remote token (and hence the file) intact.
  assert.deepStrictEqual(sb.clearAuthToken(), { ok: true, hasToken: false });
  assert.strictEqual(sb.hasAuthToken(), false);
  body = fs.readFileSync(authFile, 'utf8');
  assert.doesNotMatch(body, /CLAUDE_CODE_OAUTH_TOKEN/);
  assert.match(body, new RegExp(`^CLODEX_REMOTE_TOKEN=${remote}$`, 'm'));
});
